name: codecov
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  tarpaulin:
    name: tarpaulin
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update apt
      run: sudo apt-get update

    - name: Install netcdf
      run: sudo apt-get install libnetcdf-dev

    - name: Install rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install tarpaulin
      uses: baptiste0928/cargo-install@30f432979e99f3ea66a8fa2eede53c07063995d8  # v2.1.0
      with:
        crate: cargo-tarpaulin
        version: "0.27.3"

    - name: Tarpaulin
      run: cargo tarpaulin --verbose --out Xml --ignore-tests

    - name: Upload to codecov
      uses: codecov/codecov-action@v4.1.0
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
